### PR TITLE
fix libusb discovery on cmake

### PR DESCRIPTION
**Pull request by ra1nb0w**
should be the same of the include on

perseusfx2.h
perseus-sdr.h
perseus-in.h

### CODE REVIEW

**Comment by ra1nb0w** [comment]
ping

**Comment by f4exb** [comment]
No. it is perseusfx2.h, perseus-sdr.h, perseus-in.h that are wrong. It should be:
`#include <libusb.h>`
and not:
`#include <libusb-1.0/libusb.h>`

**Comment by ra1nb0w** [comment]
touching upstream is not good; anyway, changes done.

**Comment by f4exb** [comment]
This is my fork anyway not Andrea's official one.

**Pull request merged**
